language: ruby
cache:
  directories:
  - vendor/bundle
sudo: false
rvm:
  - '1.9'
  - '2.1'
  - '2.2'
  - '2.3'
  - '2.4'
  - '2.5'
  - 'ruby-head'
  - 'jruby'

install: bundle install --jobs=3 --retry=3

script: bundle exec rake spec

after_success:
  coveralls
