# - '2.1'
# - '2.2'
# - '2.3'
# - '2.4'
# - '2.5'
# - 'ruby-head'
# - 'jruby'

version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.1
      - test-2.2
      - test-2.3
      - test-2.4
      - test-2.5
      - test-jruby
      - test-latest
jobs:
  test-2.1: &test-template
    docker:
      - image: circleci/ruby:2.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
  test-2.2:
    <<: *test-template
    docker:
      - image: circleci/ruby:2.2
  test-2.3:
    <<: *test-template
    docker:
      - image: circleci/ruby:2.3
  test-2.4:
    <<: *test-template
    docker:
      - image: circleci/ruby:2.4
  test-2.5:
    <<: *test-template
    docker:
      - image: circleci/ruby:2.5
  test-jruby:
    <<: *test-template
    docker:
      - image: circleci/jruby:latest
        environment:
          JRUBY_OPTS: "--debug"
  test-latest:
    <<: *test-template
    docker:
      - image: circleci/ruby:latest
